import type { Metadata } from "next";
import { Anton } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const anton = Anton({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          anton.className,
          "bg-background text-text overflow-x-hidden"
        )}
      >
        {children}
      </body>
    </html>
  );
}
